language: java
jdk:
  - oraclejdk8
branches:
  only:
    - master
cache:
  directories:
    - '$HOME/.m2/repository'
script: fridge/mvn clean package
notifications:
  email:
    recipients:
      - younghokang.1121@gmail.com
