language: java
jdk:
  - oraclejdk8
branches:
  only:
    - master
cache:
  directories:
    - '$HOME/.m2/repository'
before_script: cd fridge
script: mvn clean package
notifications:
  email:
    recipients:
      - younghokang.1121@gmail.com
