spring:
  application:
    name: fridge-ui
  mail:
    host: localhost
    port: 2525
server:
  port: 8083
logging:
  level:
    org.springframework.security: DEBUG
    com.poseidon.fridge.service.FridgeClient: DEBUG
    com.poseidon.fridge.service.MemberClient: DEBUG
feign:
  client:
    config:
      default:
        loggerLevel: FULL
      fridge-member:
        errorDecoder: com.poseidon.config.MemberFeignErrorDecoder
      fridge-service:
        errorDecoder: com.poseidon.config.FridgeFeignErrorDecoder
noti:
  sender: no-reply@fridge.com
  token-expire-time: 15
  token-try-limit: 5