spring:
  application:
    name: fridge-ui
server:
  port: 8083
logging:
  level:
    org.springframework.security: DEBUG
    com.poseidon.fridge.service.FridgeClient: DEBUG
feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true
  client:
    config:
      default:
        loggerLevel: FULL
      fridge-member:
        errorDecoder: com.poseidon.config.MemberFeignErrorDecoder
      fridge-service:
        errorDecoder: com.poseidon.config.FridgeFeignErrorDecoder